# Generated by Django 2.0.4 on 2019-02-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20190203_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascto',
            name='vacuna',
            field=models.ManyToManyField(blank=True, to='mascota.Vacuna'),
        ),
    ]
